2007-10-10  James Antill  <james@and.org>
	* ustr-main.h (USTR_CNTL_MALLOC_CHECK_ENABLE): Add function.
	(USTR_CNTL_MALLOC_CHECK_MEM): Add function.
	(USTR_CNTL_MALLOC_CHECK_SZ_MEM): Add function.
	(USTR_CNTL_MALLOC_CHECK_EMPTY): Add function.

 Move some code around to use the above functions.

diff --git a/ustr-import.in b/ustr-import.in
--- a/ustr-import.in
+++ b/ustr-import.in
@@ -191,7 +191,10 @@ else
   cp "$SHRDIR/.gdbinit" .
 fi
 
-
+if $cntl && ! $cfiles; then
+ cntl=false
+ echo "Warn: Can't do dynamic configuration without cfiles." 1>&2
+fi
 
 # ---------------------------------------------
 # Copy all the files locally...
@@ -227,6 +230,7 @@ fi
 
 if $cntl; then
   copy cntl
+  cp "$SHRDIR/malloc-check.h" .
 fi
 
 # conf is generated from scratch
